### ISSUE TITLE
Webstorm supports two binaries

### ISSUE THREAD

**Issue by astoilkov** [sindresorhus/env-editor#8]
Webstorm supports both `wstorm` and `webstorm` binaries. When WebStorm has registered it as `webstorm` the `open-editor` module doesn't work.

**Comment by sindresorhus** [comment]
Can you link to some documentation about that?

**Comment by astoilkov** [comment]
Yes. You check it out [here](https://www.jetbrains.com/help/webstorm/working-with-the-ide-features-from-command-line.html#launch_from_cli) by clicking on the macOS/Linux tab where `webstorm` will show up. I think this is a recent change because we just noticed it today with my colleague when he ran the `Create Launcher Script` command.

**Comment by bundyo** [comment]
I've been working with WebStorm for years under Linux and I can't recall ever seeing wstorm before.

**Comment by erusev** [comment]
I'm on MacOS and WebStorm's binary is called `webstorm`. 

The examples in the docs also use `webstorm` and I see no mention of `wstorm`: https://www.jetbrains.com/help/webstorm/working-with-the-ide-features-from-command-line.html
